# Generated by Django 3.1.12 on 2025-10-02 07:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('cooking', 'Cooking'), ('salon', 'Salon/Beauty'), ('mechanical', 'Mechanical'), ('tailoring', 'Tailoring'), ('wireman', 'Electrical/Wiring'), ('cleaning', 'Cleaning'), ('plumbing', 'Plumbing'), ('carpentry', 'Carpentry'), ('painting', 'Painting'), ('gardening', 'Gardening'), ('other', 'Other')], max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('required_skills', models.TextField()),
                ('duration_months', models.IntegerField(default=1, help_text='Duration value')),
                ('duration_unit', models.CharField(choices=[('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months'), ('years', 'Years')], default='months', help_text='Duration unit', max_length=10)),
                ('workers_needed', models.IntegerField(default=1, help_text='Number of workers needed', validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('assigned', 'Assigned')], default='open', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True, help_text='Your proposal message. You can also record audio.', null=True)),
                ('cover_letter_audio', models.FileField(blank=True, help_text='Record your cover letter via microphone', null=True, upload_to='job_requests/audio/')),
                ('proposal_type', models.CharField(choices=[('monthly', 'Monthly'), ('daily', 'Daily'), ('hourly', 'Hourly'), ('fixed', 'Fixed Project')], default='monthly', max_length=10)),
                ('proposed_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Your proposed rate', max_digits=10, null=True)),
                ('proposed_duration', models.IntegerField(blank=True, help_text='Duration in the selected unit (months/days/hours)', null=True)),
                ('certificates', models.FileField(blank=True, help_text='Upload relevant certificates', null=True, upload_to='job_requests/certificates/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocalResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('resource_type', models.CharField(choices=[('certification', 'Certification'), ('gov_scheme', 'Government Scheme'), ('workshop', 'Local Workshop'), ('exam', 'Skill-Specific Exam'), ('community', 'Community Group'), ('youtube', 'Local YouTube Channel')], max_length=20)),
                ('relevance_tags', models.JSONField(default=list, help_text='Tags like: Dabba Service, Painter, Photographer, IT Freelancer')),
                ('credibility', models.CharField(blank=True, help_text='e.g., NSDC, Govt Portal, Industry Association', max_length=200, null=True)),
                ('url', models.URLField(max_length=500)),
                ('location', models.CharField(blank=True, help_text='City/State for local targeting', max_length=120, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('razorpay', 'Razorpay'), ('upi', 'UPI'), ('scanner', 'QR Scanner'), ('cash', 'Cash'), ('bank_transfer', 'Bank Transfer')], default='razorpay', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid (In Escrow)'), ('work_submitted', 'Work Submitted'), ('work_confirmed', 'Work Confirmed'), ('released', 'Released to Freelancer'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('disputed', 'Disputed')], default='pending', max_length=20)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=200, null=True)),
                ('is_escrow', models.BooleanField(default=True)),
                ('escrow_release_date', models.DateTimeField(blank=True, null=True)),
                ('work_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('work_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('freelancer', 'Freelancer'), ('recruiter', 'Job Recruiter')], max_length=10)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('upi_id', models.CharField(blank=True, help_text='UPI ID for receiving payments', max_length=100, null=True)),
                ('qr_code', models.ImageField(blank=True, help_text='QR code image for payments', null=True, upload_to='payments/qr_codes/')),
                ('bank_account_name', models.CharField(blank=True, help_text='Name on bank account', max_length=100, null=True)),
                ('bank_account_number', models.CharField(blank=True, help_text='Bank account number', max_length=34, null=True)),
                ('bank_ifsc', models.CharField(blank=True, help_text='IFSC / Bank identifier', max_length=20, null=True)),
                ('bank_name', models.CharField(blank=True, help_text='Bank name', max_length=100, null=True)),
                ('skills', models.TextField(blank=True, help_text='Comma-separated list of skills', null=True)),
                ('selected_skills', models.JSONField(blank=True, default=list, help_text='Selected skills from categories')),
                ('experience_years', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('submitted', 'Submitted for Review'), ('completed', 'Completed & Confirmed'), ('rejected', 'Rejected by Recruiter'), ('revision_requested', 'Revision Requested')], default='not_started', max_length=20)),
                ('completion_notes', models.TextField(blank=True, null=True)),
                ('before_photos', models.FileField(blank=True, help_text='Before work photos', null=True, upload_to='work_tracking/before/')),
                ('after_photos', models.FileField(blank=True, help_text='After work photos', null=True, upload_to='work_tracking/after/')),
                ('completion_video', models.FileField(blank=True, help_text='Completion video', null=True, upload_to='work_tracking/videos/')),
                ('work_files', models.FileField(blank=True, help_text='Additional work files', null=True, upload_to='work_tracking/files/')),
                ('recruiter_feedback', models.TextField(blank=True, null=True)),
                ('revision_notes', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_submissions', to='freelancer_platform.userprofile')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_tracking', to='freelancer_platform.payment')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('work_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('vr_video', 'VR Video')], max_length=10)),
                ('file', models.FileField(help_text='Upload photos, videos, or VR videos', upload_to='work_examples/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_examples', to='freelancer_platform.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_received', to='freelancer_platform.userprofile'),
        ),
        migrations.AddField(
            model_name='payment',
            name='job_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='freelancer_platform.jobrequest'),
        ),
        migrations.AddField(
            model_name='payment',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_made', to='freelancer_platform.userprofile'),
        ),
        migrations.AddField(
            model_name='payment',
            name='work_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_work', to='freelancer_platform.userprofile'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='freelancer_platform.userprofile'),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_requests', to='freelancer_platform.job'),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='selected_work_examples',
            field=models.ManyToManyField(blank=True, help_text='Select your previous work samples', to='freelancer_platform.WorkExample'),
        ),
        migrations.AddField(
            model_name='job',
            name='assigned_freelancer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to='freelancer_platform.userprofile'),
        ),
        migrations.AddField(
            model_name='job',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to='freelancer_platform.userprofile'),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_type', models.CharField(choices=[('recruiter_payment', 'Recruiter: Paid but no work done'), ('recruiter_quality', 'Recruiter: Work quality is poor'), ('recruiter_delay', 'Recruiter: Work not completed on time'), ('freelancer_payment', 'Freelancer: Work done but no payment'), ('freelancer_delay', 'Freelancer: Payment delayed'), ('freelancer_escrow', 'Freelancer: Payment stuck in escrow')], max_length=25)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('evidence_photos', models.FileField(blank=True, help_text='Evidence photos', null=True, upload_to='complaints/evidence/')),
                ('evidence_videos', models.FileField(blank=True, help_text='Evidence videos', null=True, upload_to='complaints/evidence/')),
                ('evidence_documents', models.FileField(blank=True, help_text='Evidence documents', null=True, upload_to='complaints/evidence/')),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('rejected', 'Rejected'), ('escalated', 'Escalated')], default='open', max_length=15)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('resolution_type', models.CharField(blank=True, choices=[('refund_recruiter', 'Refund to Recruiter'), ('release_payment', 'Release Payment to Freelancer'), ('partial_payment', 'Partial Payment'), ('no_action', 'No Action Required'), ('warning_issued', 'Warning Issued')], max_length=20, null=True)),
                ('resolution_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('complainant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints_filed', to='freelancer_platform.userprofile')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='freelancer_platform.payment')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_complaints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='jobrequest',
            unique_together={('job', 'freelancer')},
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('proposed_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=15)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='freelancer_platform.userprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='freelancer_platform.job')),
            ],
            options={
                'unique_together': {('job', 'freelancer')},
            },
        ),
    ]
