# Generated by Django 4.2.23 on 2025-08-06 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer_platform', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='budget_max',
        ),
        migrations.RemoveField(
            model_name='job',
            name='budget_min',
        ),
        migrations.RemoveField(
            model_name='job',
            name='duration',
        ),
        migrations.AddField(
            model_name='job',
            name='assigned_freelancer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to='freelancer_platform.userprofile'),
        ),
        migrations.AddField(
            model_name='job',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='duration_months',
            field=models.IntegerField(default=1, help_text='Duration in months'),
        ),
        migrations.AddField(
            model_name='job',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('cooking', 'Cooking'), ('salon', 'Salon/Beauty'), ('mechanical', 'Mechanical'), ('tailoring', 'Tailoring'), ('wireman', 'Electrical/Wiring'), ('cleaning', 'Cleaning'), ('plumbing', 'Plumbing'), ('carpentry', 'Carpentry'), ('painting', 'Painting'), ('gardening', 'Gardening'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('assigned', 'Assigned')], default='open', max_length=15),
        ),
        migrations.CreateModel(
            name='JobRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='freelancer_platform.userprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_requests', to='freelancer_platform.job')),
            ],
            options={
                'unique_together': {('job', 'freelancer')},
            },
        ),
    ]
