# Generated by Django 4.2.23 on 2025-08-06 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer_platform', '0002_remove_job_budget_max_remove_job_budget_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='selected_skills',
            field=models.JSONField(blank=True, default=list, help_text='Selected skills from categories'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skills',
            field=models.TextField(blank=True, help_text='Comma-separated list of skills', null=True),
        ),
        migrations.CreateModel(
            name='WorkExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('work_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('vr_video', 'VR Video')], max_length=10)),
                ('file', models.FileField(help_text='Upload photos, videos, or VR videos', upload_to='work_examples/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_examples', to='freelancer_platform.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
