# Generated by Django 4.2.23 on 2025-08-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer_platform', '0003_userprofile_selected_skills_alter_userprofile_skills_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobrequest',
            name='message',
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='certificates',
            field=models.FileField(blank=True, help_text='Upload relevant certificates', null=True, upload_to='job_requests/certificates/'),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='cover_letter',
            field=models.TextField(blank=True, help_text='Your proposal message. You can also record audio.', null=True),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='cover_letter_audio',
            field=models.FileField(blank=True, help_text='Record your cover letter via microphone', null=True, upload_to='job_requests/audio/'),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='proposal_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('daily', 'Daily'), ('hourly', 'Hourly'), ('fixed', 'Fixed Project')], default='monthly', max_length=10),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='proposed_duration',
            field=models.IntegerField(blank=True, help_text='Duration in the selected unit (months/days/hours)', null=True),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='proposed_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Your proposed rate', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='selected_work_examples',
            field=models.ManyToManyField(blank=True, help_text='Select your previous work samples', to='freelancer_platform.workexample'),
        ),
    ]
