# Generated by Django 4.2.7 on 2025-09-14 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('freelancer_platform', '0004_remove_jobrequest_message_jobrequest_certificates_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('razorpay', 'Razorpay'), ('cash', 'Cash'), ('bank_transfer', 'Bank Transfer')], default='razorpay', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('disputed', 'Disputed')], default='pending', max_length=15)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=200, null=True)),
                ('is_escrow', models.BooleanField(default=True)),
                ('escrow_release_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_received', to='freelancer_platform.userprofile')),
                ('job_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='freelancer_platform.jobrequest')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_made', to='freelancer_platform.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WorkTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected by Recruiter')], default='not_started', max_length=15)),
                ('completion_notes', models.TextField(blank=True, null=True)),
                ('before_photos', models.FileField(blank=True, help_text='Before work photos', null=True, upload_to='work_tracking/before/')),
                ('after_photos', models.FileField(blank=True, help_text='After work photos', null=True, upload_to='work_tracking/after/')),
                ('completion_video', models.FileField(blank=True, help_text='Completion video', null=True, upload_to='work_tracking/videos/')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_submissions', to='freelancer_platform.userprofile')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_tracking', to='freelancer_platform.payment')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_type', models.CharField(choices=[('recruiter_payment', 'Recruiter: Paid but no work done'), ('recruiter_quality', 'Recruiter: Work quality is poor'), ('freelancer_payment', 'Freelancer: Work done but no payment'), ('freelancer_delay', 'Freelancer: Payment delayed')], max_length=25)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('evidence_photos', models.FileField(blank=True, help_text='Evidence photos', null=True, upload_to='complaints/evidence/')),
                ('evidence_videos', models.FileField(blank=True, help_text='Evidence videos', null=True, upload_to='complaints/evidence/')),
                ('evidence_documents', models.FileField(blank=True, help_text='Evidence documents', null=True, upload_to='complaints/evidence/')),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('rejected', 'Rejected'), ('escalated', 'Escalated')], default='open', max_length=15)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('resolution_type', models.CharField(blank=True, choices=[('refund_recruiter', 'Refund to Recruiter'), ('release_payment', 'Release Payment to Freelancer'), ('partial_payment', 'Partial Payment'), ('no_action', 'No Action Required'), ('warning_issued', 'Warning Issued')], max_length=20, null=True)),
                ('resolution_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('complainant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints_filed', to='freelancer_platform.userprofile')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='freelancer_platform.payment')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_complaints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
