# Generated by Django 4.2.23 on 2025-09-13 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer_platform', '0005_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
