# Generated by Django 4.2.23 on 2025-09-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer_platform', '0005_payment_worktracking_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='duration_unit',
            field=models.CharField(choices=[('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months'), ('years', 'Years')], default='months', help_text='Duration unit', max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='duration_months',
            field=models.IntegerField(default=1, help_text='Duration value'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('razorpay', 'Razorpay'), ('upi', 'UPI'), ('scanner', 'QR Scanner'), ('cash', 'Cash'), ('bank_transfer', 'Bank Transfer')], default='razorpay', max_length=20),
        ),
    ]
