# Generated by Django 4.2.23 on 2025-09-14 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer_platform', '0006_job_duration_unit_alter_job_duration_months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='work_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='work_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_work', to='freelancer_platform.userprofile'),
        ),
        migrations.AddField(
            model_name='payment',
            name='work_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worktracking',
            name='recruiter_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worktracking',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worktracking',
            name='revision_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worktracking',
            name='work_files',
            field=models.FileField(blank=True, help_text='Additional work files', null=True, upload_to='work_tracking/files/'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_type',
            field=models.CharField(choices=[('recruiter_payment', 'Recruiter: Paid but no work done'), ('recruiter_quality', 'Recruiter: Work quality is poor'), ('recruiter_delay', 'Recruiter: Work not completed on time'), ('freelancer_payment', 'Freelancer: Work done but no payment'), ('freelancer_delay', 'Freelancer: Payment delayed'), ('freelancer_escrow', 'Freelancer: Payment stuck in escrow')], max_length=25),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid (In Escrow)'), ('work_submitted', 'Work Submitted'), ('work_confirmed', 'Work Confirmed'), ('released', 'Released to Freelancer'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('disputed', 'Disputed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='worktracking',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('submitted', 'Submitted for Review'), ('completed', 'Completed & Confirmed'), ('rejected', 'Rejected by Recruiter'), ('revision_requested', 'Revision Requested')], default='not_started', max_length=20),
        ),
    ]
