# Generated by Django 4.2.23 on 2025-09-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer_platform', '0007_payment_work_confirmed_at_payment_work_confirmed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cover_letter',
            field=models.TextField(blank=True, null=True),
        ),
    ]
