# Generated by Django 4.2.23 on 2025-09-15 16:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer_platform', '0009_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='workers_needed',
            field=models.IntegerField(default=1, help_text='Number of workers needed', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='qr_code',
            field=models.ImageField(blank=True, help_text='QR code image for payments', null=True, upload_to='payments/qr_codes/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='upi_id',
            field=models.CharField(blank=True, help_text='UPI ID for receiving payments', max_length=100, null=True),
        ),
    ]
