# Generated by Django 4.2.23 on 2025-09-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer_platform', '0010_job_workers_needed_userprofile_qr_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bank_account_name',
            field=models.CharField(blank=True, help_text='Name on bank account', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, help_text='Bank account number', max_length=34, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bank_ifsc',
            field=models.CharField(blank=True, help_text='IFSC / Bank identifier', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Bank name', max_length=100, null=True),
        ),
    ]
