# Generated by Django 4.2.23 on 2025-09-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer_platform', '0011_userprofile_bank_account_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('resource_type', models.CharField(choices=[('certification', 'Certification'), ('gov_scheme', 'Government Scheme'), ('workshop', 'Local Workshop'), ('exam', 'Skill-Specific Exam'), ('community', 'Community Group'), ('youtube', 'Local YouTube Channel')], max_length=20)),
                ('relevance_tags', models.JSONField(default=list, help_text='Tags like: Dabba Service, Painter, Photographer, IT Freelancer')),
                ('credibility', models.CharField(blank=True, help_text='e.g., NSDC, Govt Portal, Industry Association', max_length=200, null=True)),
                ('url', models.URLField(max_length=500)),
                ('location', models.CharField(blank=True, help_text='City/State for local targeting', max_length=120, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
